### Post Request
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "John",
    "password": "password"
}

### Post Request
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "John",
    "password": "passwordasdasd"
}
