### Register an account
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "John",
    "password": "password"
}

### Login, this will return a sessionId cookie
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "John",
    "password": "password"
}
